import 'package:flutter/widgets.dart';
// Generated by `flutter gen-l10n` into lib/l10n/ — see l10n.yaml. Not the old
// `package:flutter_gen/gen_l10n/...` synthetic-package path: current Flutter has
// removed synthetic package generation, so that import resolves to nothing and
// takes every `context.l10n` call site down with it.
import '../../l10n/app_localizations.dart';

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this)!;
}
